NDefines.NProduction.DEFAULT_MAX_NAV_FACTORIES_PER_LINE = 10 -- 5
NDefines.NProduction.CAPITAL_SHIP_MAX_NAV_FACTORIES_PER_LINE = 10 -- 5
NDefines.NNavy.MAX_POSITIONING_PENALTY_FROM_HIGHER_SHIP_RATIO = 0.5 -- 1
NDefines.NNavy.HIGHER_SHIP_RATIO_POSITIONING_PENALTY_FACTOR = 0.25 -- 0.5

NDefines.NProduction.CIC_BANK_SPEED_BOOST_FACTOR = 0.12 -- 0
NDefines.NMarket.IC_TO_CIC_FACTOR = 1.0 -- 0.5
NDefines.NMarket.PURCHASE_CONTRACT_DELIVERY_TOTAL_DAYS = 30 -- 60
NDefines.NMarket.MAX_CIV_FACTORIES_PER_CONTRACT = 15 -- 1